name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: goutamtak
        password: rockonjasmin

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: goutamtak/ragmodelimage:latest
        context: .
        file: ./Dockerfile
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: goutamtak/ragModelImage:latest
        context: .
        file: ./Dockerfile
